micronaut:
  application:
    name: Localsense - Aggregator
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
      main:
        paths: classpath:views
        mapping: /live/**
netty:
  default:
    allocator:
      max-order: 3
graphql:
  enabled: true
  graphiql:
    enabled: true
endpoints:
  all:
    enabled: true
    sensitive: false
  stop:
    enabled: false
